
import { School } from './types';

export const schools: School[] = [
  {
    id: 1,
    name: "مدرسة العربي للتكنولوجيا التطبيقية",
    governorate: "المنوفية",
    city: "قويسنا",
    specialty: "تكنولوجيا الكهرباء • تكنولوجيا الميكانيكا • تكنولوجيا التبريد والتكييف • اللوجستيات",
    industrialPartner: "مجموعة شركات ومصانع العربي",
    startDate: "2018/2019",
    establishedYears: 7,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "كفر الرمل المنطقة الصناعية الثالثة قويسنا",
    mapUrl: "https://maps.app.goo.gl/NPksKXXZGPenZCSe8",
    acceptanceRegions: "قويسنا ـ شببين الكوم ( المنوفية) - بنها ( القليوبية )",
    gender: "بنين",
    lat: 30.5600,
    lng: 31.1400
  },
  {
    id: 2,
    name: "مدرسة الامام محمد متولى الشعراوي للتكنولوجيا التطبيقية",
    governorate: "القاهرة",
    city: "القاهرة الجديدة",
    specialty: "الشبكات المتخصصة للمنشآت • التبريد والتكييف • أنظمة الكهرباء المتكاملة • التشطيبات والصيانة المعمارية",
    industrialPartner: "مجموعة شركات طلعت مصطفى",
    startDate: "2018/2019",
    establishedYears: 7,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "التجمع الثالث بجوار قسم القطامية",
    mapUrl: "https://maps.app.goo.gl/mgq11S7vJDFyb38v5",
    acceptanceRegions: "القاهرة",
    gender: "مشترك",
    lat: 30.0075,
    lng: 31.4285
  },
  {
    id: 3,
    name: "التكنولوجيا التطبيقية للميكاترونيات (بدر)",
    governorate: "القاهرة",
    city: "بدر",
    specialty: "أنظمة الميكاترونيات",
    industrialPartner: "شركة ايجي ترافو",
    startDate: "2018/2019",
    establishedYears: 7,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "الحي الثامن مدينة بدر خلف الجامعة الروسية",
    mapUrl: "https://maps.app.goo.gl/v1y9WSAdsYcKK6yx9",
    acceptanceRegions: "القاهرة - الجيزة - القليوبية - الشرقية ( العاشر من رمضان )",
    gender: "مشترك",
    lat: 30.1381,
    lng: 31.7142
  },
  {
    id: 4,
    name: "مدرسة الإنتاج الحربي للتكنولوجيا التطبيقية بحلوان",
    governorate: "القاهرة",
    city: "حلوان",
    specialty: "صيانة واصلاح السيارات • تشكيل ولحام المعادن • صيانه ميكانيكيه و هيدروليك • سباكه المعادن",
    industrialPartner: "وزارة الإنتاج الحربي",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "تقبل طلاب جدد",
    insideFactory: true,
    address: "عين حلوان داخل مصنع 99الحربى",
    mapUrl: "https://maps.app.goo.gl/7RCZAFW7ZtjoHCTGA",
    acceptanceRegions: "القاهرة - الجيزة - القليوبية ( شبرا الخيمة )",
    gender: "بنين",
    lat: 29.8400,
    lng: 31.3000
  },
  {
    id: 5,
    name: "مدرسة الإنتاج الحربي للتكنولوجيا التطبيقية بالسلام",
    governorate: "القاهرة",
    city: "السلام",
    specialty: "تكنولوجيا الكهرباء والالكترونيات • تكنولوجيا الميكانيكا",
    industrialPartner: "وزارة الإنتاج الحربي",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "تقبل طلاب جدد",
    insideFactory: true,
    address: "اول طريق بلبيس الصحراوي المجمع التكنولوجي المتكامل",
    mapUrl: "https://maps.app.goo.gl/ruWHSMRrdR7AAKeAA",
    acceptanceRegions: "جميع المحافظات",
    gender: "مشترك",
    lat: 30.1700,
    lng: 31.4300
  },
  {
    id: 6,
    name: "مدرسة السويدي للتكنولوجيا التطبيقية بديرب نجم",
    governorate: "الشرقية",
    city: "ديرب نجم",
    specialty: "تكنولوجيا الكهرباء • تكنولوجيا الميكانيكا",
    industrialPartner: "مؤسسة ال السويدى للتنمية",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "محافظة الشرقية – إدارة ديرب نجم امام مجمع المحاكم",
    mapUrl: "https://maps.app.goo.gl/vUpvfk8osyK97dup6",
    acceptanceRegions: "الشرقية",
    gender: "مشترك",
    lat: 30.7327,
    lng: 31.7133
  },
  {
    id: 7,
    name: "مدرسة الشهيد النقيب احمد تعلب الفندقية",
    governorate: "القاهرة",
    city: "شرق مدينة نصر",
    specialty: "إدارة وتشغيل مطاعم • قدرات تجارية مكملة",
    industrialPartner: "مطاعم ماكدونلز",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "ميدان هشام بركات ش بن حوقل",
    gender: "مشترك",
    lat: 30.0550,
    lng: 31.3450,
    acceptanceRegions: "القاهرة - الجيزة - القليوبية"
  },
  {
    id: 8,
    name: "مدرسة إلكترو مصر للتكنولوجيا التطبيقية",
    governorate: "القاهرة",
    city: "السلام",
    specialty: "صيانة كهربية • الأتمتة الصناعية",
    industrialPartner: "شنايدر إلكتريك",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "خلف مساكن العبد 700 مدينة السلام",
    gender: "مشترك",
    lat: 30.1750,
    lng: 31.4350,
    acceptanceRegions: "القاهرة ــ القليوبية"
  },
  {
    id: 9,
    name: "مدرسة ايجيبت جولد للتكنولوجيا التطبيقية",
    governorate: "القليوبية",
    city: "العبور",
    specialty: "الحلي والمجوهرات",
    industrialPartner: "شركة ايجيبت جولد",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "مدينة العبور شارع 117",
    gender: "مشترك",
    lat: 30.2200,
    lng: 31.4700,
    acceptanceRegions: "القاهرة - الجيزة - القليوبية"
  },
  {
    id: 10,
    name: "مدرسة الصالحية الزراعية للتكنولوجيا التطبيقية",
    governorate: "الشرقية",
    city: "الصالحية",
    specialty: "تكنولوجيا الانتاج الحيواني والداجنى • تكنولوجيا الزراعة والري",
    industrialPartner: "شركة الصالحية للاستثمار الزراعي",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "الصالحية الجديدة بجوار محطة الصرف",
    gender: "بنين",
    lat: 30.6400,
    lng: 31.9100,
    acceptanceRegions: "الشرقية - الاسماعيلية"
  },
  {
    id: 11,
    name: "مدرسة اى تك للتكنولوجيا التطبيقية",
    governorate: "القاهرة",
    city: "الشروق",
    specialty: "تكنولوجيا المعلومات والحاسبات",
    industrialPartner: "شركة IBM ومؤسسة الألفي",
    startDate: "2019/2020",
    establishedYears: 6,
    status: "لا تقبل طلاب جدد",
    insideFactory: false,
    address: "مدينة الشروق",
    gender: "مشترك",
    lat: 30.1100,
    lng: 31.6100,
    acceptanceRegions: "القاهرة"
  },
  {
    id: 12,
    name: "مدرسة بي تك للتكنولوجيا التطبيقية",
    governorate: "القاهرة",
    city: "الخليفة والمقطم",
    specialty: "الامداد والخدمات اللوجيستية • التسويق • المبيعات",
    industrialPartner: "شركة بي تك للتجارة والتوزيع",
    startDate: "2020/2021",
    establishedYears: 5,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "حي الاسمرات بالمقطم ش احمد فؤاد نجم",
    gender: "مشترك",
    lat: 30.0150,
    lng: 31.2950,
    acceptanceRegions: "القاهرة - الجيزة"
  },
  {
    id: 13,
    name: "مدرسة وي للتكنولوجيا التطبيقية - مدينة نصر",
    governorate: "القاهرة",
    city: "شرق مدينة نصر",
    specialty: "أنظمة الإتصالات • الشبكات و امن المعلومات • تطوير مواقع وبرمجيات",
    industrialPartner: "شركة المصرية للاتصالات",
    startDate: "2020/2021",
    establishedYears: 5,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "75ش ابن المهدي اخر سور الحديقة الدولية",
    gender: "مشترك",
    lat: 30.0500,
    lng: 31.3300,
    acceptanceRegions: "القاهرة"
  },
  {
    id: 14,
    name: "مدرسة ريادة للتكنولوجيا التطبيقية",
    governorate: "بورسعيد",
    city: "بحر البقر",
    specialty: "تكنولوجيا انتاج وتصنيع الالبان",
    industrialPartner: "شركة بورسعيد للتصنيع الغذائي – ريادة",
    startDate: "2020/2021",
    establishedYears: 5,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "قرية الصدق بجوار حي جنوب",
    gender: "مشترك",
    lat: 31.1000,
    lng: 32.2000,
    acceptanceRegions: "بور سعيد"
  },
  {
    id: 15,
    name: "مدرسة الفنون للتكنولوجيا التطبيقية",
    governorate: "الجيزة",
    city: "العمرانية",
    specialty: "تكنولوجيا تصنيع وتحريك الديكور • اضاءة • تصوير • ماكياج",
    industrialPartner: "أكاديمية الفنون",
    startDate: "2020/2021",
    establishedYears: 5,
    status: "تقبل طلاب جدد",
    insideFactory: true,
    address: "ش جمال الدين الأفغانى العمرانية",
    gender: "مشترك",
    lat: 29.9950,
    lng: 31.2050,
    acceptanceRegions: "القاهرة - الجيزة - القليوبية - الفيوم - ببني سويف"
  },
  {
    id: 16,
    name: "مدرسة فولكس فاجن للتكنولوجيا التطبيقية",
    governorate: "القاهرة",
    city: "الخليفة والمقطم",
    specialty: "صيانة واصلاح السيارات ( مركبات خفيفة)",
    industrialPartner: "مجموعة فولكس فاجن",
    startDate: "2021/2022",
    establishedYears: 4,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "حي الاسمرات بالمقطم ش احمد فؤاد نجم",
    gender: "مشترك",
    lat: 30.0160,
    lng: 31.2960,
    acceptanceRegions: "القاهرة - الجيزة"
  },
  {
    id: 17,
    name: "مدرسة غبور 1 للتكنولوجيا التطبيقية",
    governorate: "القاهرة",
    city: "15 مايو",
    specialty: "صيانة واصلاح السيارات • صيانة شبكات ودعم فني",
    industrialPartner: "مؤسسة غبور للتنمية",
    startDate: "2021/2022",
    establishedYears: 4,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "امتداد مدينة 15 مايو المجاورة 4",
    gender: "مشترك",
    lat: 29.8300,
    lng: 31.3700,
    acceptanceRegions: "جميع المحافظات"
  },
  {
    id: 18,
    name: "مدرسة غبور 2 للتكنولوجيا التطبيقية",
    governorate: "الجيزة",
    city: "6 اكتوبر",
    specialty: "صيانة واصلاح السيارات • تطوير وصيانة برمجيات",
    industrialPartner: "مؤسسة غبور للتنمية",
    startDate: "2021/2022",
    establishedYears: 4,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "الحي السادس مدينة 6 اكنوبر",
    gender: "مشترك",
    lat: 29.9700,
    lng: 30.9400,
    acceptanceRegions: "جميع المحافظات"
  },
  {
    id: 19,
    name: "مدرسة ظهر للتكنولوجيا التطبيقية",
    governorate: "بورسعيد",
    city: "شمال بور سعيد",
    specialty: "صيانة كهربية • الشبكات وتكنولوجيا المعلومات • تشغيل وصيانة المعدات",
    industrialPartner: "أكاديمية السويدى الفنية",
    startDate: "2021/2022",
    establishedYears: 4,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "أمام مساكن الحرية حي المناخ",
    gender: "مشترك",
    lat: 31.2600,
    lng: 32.2900,
    acceptanceRegions: "جميع المحافظات"
  },
  {
    id: 20,
    name: "مدرسة وي للتكنولوجيا التطبيقية بالشيخ زايد",
    governorate: "الجيزة",
    city: "الشيخ زايد",
    specialty: "أنظمة الإتصالات • الشبكات و امن المعلومات",
    industrialPartner: "شركة المصرية للاتصالات",
    startDate: "2021/2022",
    establishedYears: 4,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "الحي السادس خلف المعهد الازهري",
    gender: "مشترك",
    lat: 30.0500,
    lng: 30.9700,
    acceptanceRegions: "الجيزة - الفيوم"
  },
  {
    id: 21,
    name: "مدرسة وي للتكنولوجيا التطبيقية بالاسكندرية",
    governorate: "الاسكندرية",
    city: "شرق الاسكندرية",
    specialty: "أنظمة الإتصالات • الشبكات و امن المعلومات",
    industrialPartner: "شركة المصرية للاتصالات",
    startDate: "2021/2022",
    establishedYears: 4,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "1ش ابو النواتير سيدي جابر",
    gender: "مشترك",
    lat: 31.2200,
    lng: 29.9400,
    acceptanceRegions: "الاسكندرية - مطروح"
  },
  {
    id: 25,
    name: "مدرسة MCV للتكنولوجيا التطبيقية",
    governorate: "الشرقية",
    city: "الصالحية",
    specialty: "اللحام • صيانة المعدات الكهربية والميكانيكية",
    industrialPartner: "شركة MCV",
    startDate: "2021/2022",
    establishedYears: 4,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "الصالحية الجديدة شارع التوبة",
    gender: "مشترك",
    lat: 30.6410,
    lng: 31.9110,
    acceptanceRegions: "القاهرة - الشرقية الاسماعيلية - الدقهلية"
  },
  {
    id: 30,
    name: "مدرسة السويدي الدولية للتكنولوجيا التطبيقية",
    governorate: "الجيزة",
    city: "حدائق اكتوبر",
    specialty: "تطوير برمجيات • تكنولوجيا المعلومات",
    industrialPartner: "شركة السويدي إلكترو ميتر",
    startDate: "2022/2023",
    establishedYears: 3,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "حدائق اكتوبر",
    gender: "مشترك",
    lat: 29.9000,
    lng: 31.0500,
    acceptanceRegions: "جميع المحافظات"
  },
  {
    id: 46,
    name: "مدرسة الهيئة العربية للتصنيع للتكنولوجيا التطبيقية",
    governorate: "القاهرة",
    city: "حلوان",
    specialty: "تصنيع وصيانة الطائرات",
    industrialPartner: "الهيئة العربية للتصنيع",
    startDate: "2023/2024",
    establishedYears: 2,
    status: "تقبل طلاب جدد",
    insideFactory: true,
    address: "طريق الورش بالعزبة البحرية",
    gender: "مشترك",
    lat: 29.8500,
    lng: 31.3100,
    acceptanceRegions: "القاهرة - الجيزة - القليوبية"
  },
  {
    id: 60,
    name: "المدرسة الفنية المتقدمة للتكنولوجيا التطبيقية للطاقة النووية",
    governorate: "مرسى مطروح",
    city: "الضبعة",
    specialty: "ميكانيكا وكهرباء وتكنولوجيا نووية",
    industrialPartner: "هيئة الطاقة النووية",
    startDate: "2023/2024",
    establishedYears: 2,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "مدينة الضبعة الطريق الساحلي الدولي",
    gender: "بنين",
    lat: 31.0300,
    lng: 28.4300,
    acceptanceRegions: "جميع المحافظات"
  },
  {
    id: 79,
    name: "مدرسة بنك مصر للتكنولوجيا التطبيقية لسلامة وجودة الغذاء",
    governorate: "الجيزة",
    city: "حدائق اكتوبر",
    specialty: "تكنولوجيا الصناعات الغذائية",
    industrialPartner: "اتحاد الصناعات - مؤسسة التعليم المتوازن",
    startDate: "2024/2025",
    establishedYears: 1,
    status: "تقبل طلاب جدد",
    insideFactory: false,
    address: "منطقة 390 فدان حدائق أكتوبر",
    gender: "مشترك",
    lat: 29.9100,
    lng: 31.0600,
    acceptanceRegions: "القاهرة - الجيزة"
  }
];
